// Mocks generated by Mockito 5.4.0 from annotations
// in appexample/test/features/favorites/domain/usecases/add_favorite_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:either_dart/either.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:appexample/features/favorites/domain/entities/favorite_entity.dart' as _i7;
import 'package:appexample/features/favorites/domain/entities/reponsealias_dto.dart' as _i6;
import 'package:appexample/features/favorites/domain/errors/favoritesexceptions.dart' as _i5;
import 'package:appexample/features/favorites/domain/repositories/favorites_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock implements _i3.FavoritesRepository {
  @override
  _i4.Future<_i2.Either<_i5.ExceptionAddFavorite, _i6.ResponseAliasDTO>> addFavorite(String? link) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [link],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ExceptionAddFavorite, _i6.ResponseAliasDTO>>.value(
            _FakeEither_0<_i5.ExceptionAddFavorite, _i6.ResponseAliasDTO>(
          this,
          Invocation.method(
            #addFavorite,
            [link],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Either<_i5.ExceptionAddFavorite, _i6.ResponseAliasDTO>>.value(
            _FakeEither_0<_i5.ExceptionAddFavorite, _i6.ResponseAliasDTO>(
          this,
          Invocation.method(
            #addFavorite,
            [link],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ExceptionAddFavorite, _i6.ResponseAliasDTO>>);
  @override
  _i4.Future<_i2.Either<_i5.ExceptionGetFavorite, _i7.Favorite>> getFavorite(String? link) => (super.noSuchMethod(
        Invocation.method(
          #getFavorite,
          [link],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ExceptionGetFavorite, _i7.Favorite>>.value(
            _FakeEither_0<_i5.ExceptionGetFavorite, _i7.Favorite>(
          this,
          Invocation.method(
            #getFavorite,
            [link],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Either<_i5.ExceptionGetFavorite, _i7.Favorite>>.value(
            _FakeEither_0<_i5.ExceptionGetFavorite, _i7.Favorite>(
          this,
          Invocation.method(
            #getFavorite,
            [link],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ExceptionGetFavorite, _i7.Favorite>>);
}
